# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Build Python application and Publish Python 🐍 distributions 📦 to PyPI and TestPyPI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  create:
    branches: [ master ]
env:
  NODE_VERSION: '10.x'                #  set this to the node version to use
jobs:
  build:
    name: Conduct "Static analysis, Test & Coverage, Spell check, Mutation testing " for 🐍 code
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
        node-version: ${{ env.NODE_VERSION }}
    - name: Install dependencies Conduct Static analysis Test Coverage Mutation
      run: |
        python3 build_scripts/dependencies_static_analysis_test_cov.py

  publish:
    name: Build , Smoke test , Performance test, and publish Python 🐍 distributions 📦 to PyPI and TestPyPI
    needs: build
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: Fetch all history for all tags and branches
      run: git fetch --prune --unshallow
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install the dependencies
      run: |
        python3 build_scripts/install_dependencies.py
    - name: Build a binary wheel and a source tarball
      run: |
        python3 setup.py sdist bdist_wheel
    - name: Publish distribution 📦 to Test PyPI
      uses: pypa/gh-action-pypi-publish@master
      with:
        password: ${{ secrets.test_pypi_password }}
        repository_url: https://test.pypi.org/legacy/
    - name: Publish distribution 📦 to PyPI
      if: startsWith(github.ref, 'refs/tags')
      uses: pypa/gh-action-pypi-publish@master
      with:
        password: ${{ secrets.pypi_password }}
